<a href="https://colab.research.google.com/github/thelionthelion/eth_ntifi/blob/main/NTIFI_Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Technologies in Banking and Finance
* ETH Zurich
* Machine Learning Coding Exercises

## Task 1


Choose numbers J, K ≥ 5000 and simulate J + K vectors xj = (xj1, xj2, xj3) ∈ R3 with
* xj1 = age in [18, 80]
* xj2 = monthly income in CHF 1000 in [1, 15]
* xj3 = salaried/self-employed in {0, 1}

Compute the empirical means of xj1, xj2 and xj3 over j = 1,...,J.
Give two additional features which you believe are relevant for credit risk assessment in reality.

Explain your answer.

In [2]:
#%tensorflow_version 1.x
import numpy as np
import tensorflow as tf

from keras.models import Sequential
from keras.layers import Input, Dense, Conv2D, Concatenate, Dropout, Subtract, \
                        Flatten, MaxPooling2D, Multiply, Lambda, Add, Dot
from keras.backend import constant
from keras import optimizers

#from keras.engine.topology import Layer
from keras.models import Model
from keras.layers import Input
from keras import initializers
from keras.constraints import max_norm
import keras.backend as K
import matplotlib.pyplot as plt
import copy

1a) Choose numbers J, K ≥ 5000 and simulate J + K vectors...

In [24]:
J = 10000
K = 5000

import numpy as np

rng = np.random.Generator(np.random.PCG64())
rng = np.random.default_rng(seed=1987)
# uniform from 0 to 1 value = rng.random()
# generate 10 Gaussian random number value = rng.standard_normal(10)

# generate 20 random integers between 0 and 10
ages = rng.integers(low=18, high=80, size=J)
incomes = rng.integers(low=1, high=15, size=J)
salaried = rng.binomial(n=1, p= 0.5, size=J)
print(ages)
print(incomes)
print(salaried)

[38 34 63 ... 33 41 64]
[ 5 11  7 ...  4 13  8]
[0 1 0 ... 0 0 1]


Compute the empirical means of xj1, xj2 and xj3 over j = 1,...,J.

In [25]:
agesMean = np.mean(ages)
incomesMean = np.mean(incomes)
salariedMean = np.mean(salaried)
print(agesMean)
print(incomesMean)
print(salariedMean)


48.2658
7.4075
0.5066


Give two additional features which you believe are relevant for credit risk assessment in reality. Explain your answer.